services:
  backend:
    image: ghcr.io/${REPO_OWNER:-usedelta-ai}/deltacore/backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8088
      - NODE_ENV=production
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - PASS_KEY=${PASS_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - delta
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.backend.rule=Host(`api.${DOMAIN:-delta.vps-kinghost.net}`)
        - traefik.http.routers.backend.entrypoints=websecure
        - traefik.http.routers.backend.tls.certresolver=letsencryptresolver
        - traefik.http.services.backend.loadbalancer.server.port=8088

  frontend:
    image: ghcr.io/${REPO_OWNER:-usedelta-ai}/deltacore/frontend:latest
    networks:
      - delta
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.frontend.rule=Host(`app.${DOMAIN:-delta.vps-kinghost.net}`)
        - traefik.http.routers.frontend.entrypoints=websecure
        - traefik.http.routers.frontend.tls.certresolver=letsencryptresolver
        - traefik.http.services.frontend.loadbalancer.server.port=80

networks:
  delta:
    external: true
    name: Delta
